name: Scrape NETTV EPG

on:
  workflow_dispatch:
  schedule:
    - cron: '15 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4.1.1 

      - name: setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10.7'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: execute py script
        run: 
            python epg.py
          
      - name: commit files
        run: |
          git config --local user.email "prabesh01@pm.me"
          git config --local user.name "Prabesh01"
          git add -A
          git diff-index --quiet HEAD || git commit -a -m "scraped epg - $(date +'%Y-%m-%d')" --allow-empty
          
      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
